### DISCUSSION TITLE
新版小狼毫可能引入的一些东西

### DISCUSSION THREAD

**Discussion by yanhuacuo** [pdog18/Soak#4] [General]
新版小狼毫可能引入的一些东西：

https://github.com/fxliang/weasel

大佬修改的版本，已经很多人在用了：

```
  amber-2:
    name: 琥珀-新绿／Amber-green
    author: 五笔小筑 <wubixiaozhu@126.com>
    text_color: 0xffffff #默认文字颜色
    back_color: 0x72D4BD #候选窗背景色
    border_color: 0x00444444 #候选窗边框颜色
    candidate_back_color: 0x72D4BD #非高亮候选背景颜色    
    comment_text_color: 0xffffff #opencc注解颜色
    candidate_shadow_color: 0x00000000 #非高亮候选背景块阴影颜色
    candidate_text_color: 0xffffff #非高亮候选文字颜色
    label_color: 0xffffff #非高亮候选序数值颜色
    hilited_candidate_border_color: 0xc227BA53 #高亮候选背景块描边色
    hilited_candidate_shadow_color: 0xabD41789 #高亮候选背景块阴影颜色
    hilited_label_color: 0xffffff #高亮候选的序数值颜色
    hilited_mark_color: 0xDE33C1 #标记高亮的标签小竖块的颜色
    hilited_shadow_color: 0xab2EFF58 #编码背景块阴影颜色
    hilited_text_color: 0x82e6ca #编码文字颜色
    hilited_back_color: 0x27BA53 #编码背景颜色
    hilited_candidate_text_color: 0xffffff #高亮候选文字颜色
    hilited_candidate_back_color: 0xc227BA53 #高亮候选背景颜色
    shadow_color: 0xab2EFF58 #候选窗阴影色，默认全透明（无阴影）
```

![琥珀-新绿](https://raw.githubusercontent.com/yanhuacuo/css/master/pic/weasel-11.png)

```
98wb-pink:
  name: 一品红／98wb-pink
  author: 五笔小筑 <wubixiaozhu@126.com>
  text_color: 0xffffff #默认文字颜色
  back_color: 0xabE8CB3C #候选窗背景色
  border_color: 0xE8CB3C #候选窗边框颜色
  candidate_back_color: 0x00000000 #非高亮候选背景颜色    
  comment_text_color: 0xffffff #opencc注解颜色
  label_color: 0xffffff #非高亮候选序数值颜色
  candidate_shadow_color: 0x00000000 #非高亮候选背景块阴影颜色
  candidate_text_color: 0xffffff #非高亮候选文字颜色
  hilited_candidate_border_color: 0xE82EE8 #高亮候选背景块描边色
  hilited_candidate_shadow_color: 0xab13E8E8 #高亮候选背景块阴影颜色
  hilited_label_color: 0xffffff #高亮候选的序数值颜色
  hilited_mark_color: 0xDE33C1 #标记高亮的标签小竖块的颜色
  hilited_shadow_color: 0xab187BDD #编码背景块阴影颜色
  hilited_text_color: 0x82e6ca #编码文字颜色
  hilited_back_color: 0x42BA2CDD #编码背景颜色
  hilited_candidate_text_color: 0xffffff #高亮候选文字颜色
  hilited_candidate_back_color: 0xa1E82EE8 #高亮候选背景颜色
  shadow_color: 0xab13E868 #候选窗阴影色，默认全透明（无阴影）
```

![一品红](https://raw.githubusercontent.com/yanhuacuo/css/master/pic/01.png)
