### DISCUSSION TITLE
鼠须管和小狼毫的主题方案上的一些区别

### DISCUSSION THREAD

**Discussion by pdog18** [pdog18/Soak#5] [General]
1. 鼠须管默认   style/inline_preedit: true # 内嵌编码行

**Comment by pdog18** [comment]
2. 鼠须管似乎无法通过 spacing 来调整横向(linear)布局的候选词之间的间距，只能调整垂直方向的行间距

**Comment by yanhuacuo** [comment]
可以实现，但是，是用渲染空格实现的：

https://github.com/rime/squirrel/blob/master/data/squirrel.yaml

``````
  mojave_dark:
    name: 沙漠夜／Mojave Dark
    author: xiehuc <xiehuc@gmail.com>
    horizontal: true                        # 水平排列
    inline_preedit: true                    # 单行显示，false双行显示
    candidate_format: "%c\u2005%@"    # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间。

``````

1/3em空格 → \u2004
1/4em空格 → \u2005
1/6em空格 → \u2006

供参考
