### DISCUSSION TITLE
新上线的颜色竟然是纯数值，求问这是合法的格式吗？

### DISCUSSION THREAD

**Discussion by yanhuacuo** [pdog18/Soak#6] [General]
```
patch:
  style/color_scheme: soak
  preset_color_schemes:
    soak:
      name: 碧水／Aqua
      author: 佛振 <chen.sst@gmail.com>
      text_color: 5444061
      back_color: 14273367
      border_color: 8332994
      label_color: 9199681
      hilited_text_color: 7237681
      hilited_back_color: 16541357
      candidate_text_color: 8921247
      comment_text_color: 5161505
      hilited_candidate_text_color: 4054303
      hilited_comment_text_color: 10917119
      hilited_candidate_back_color: 10170919
      hilited_label_color: 3939250
```

**Comment by pdog18** [comment]
小狼毫完全没问题的，可以用的，会让人觉得不舒服？问题在于 json 不支持 16 进制值，很麻烦，单独颜色值转为 16进制很麻烦，既然可用，我就懒得搞了。

**Reply by yanhuacuo** [reply]
> 小狼毫完全没问题的，可以用的，会让人觉得不舒服？问题在于 json 不支持 16 进制值，很麻烦，单独颜色值转为 16进制很麻烦，既然可用，我就懒得搞了。

确实可以用，但是不清楚这是什么原理，哈哈，看到它和内置的16进行不同，觉得好奇。
内置的16进行，还不是 RGB 的顺序，是 BGR 倒过来的。

```
  luna:
    name: 明月／Luna
    author: 佛振 <chen.sst@gmail.com>
    text_color: 0x000000
    back_color: 0xffffff
    border_color: 0xcccccc
    hilited_text_color: 0x000000
    hilited_back_color: 0x7fffff
    hilited_candidate_text_color: 0xffffff
    hilited_candidate_back_color: 0x000000
```
